---
version: "3.8"
services:
  app:
    image: laravel:8-alpine
    build:
        context: ../
        dockerfile: _infra/Dockerfile
    container_name: tracking_app
    command: >-
      sh -c "
        apk add php82-pecl-xdebug && composer install ;\
        cp _infra/configs/php.ini-development /etc/php82/php.ini ;\
        cp _infra/configs/xdebug.ini /etc/php82/conf.d/50_xdebug.ini ;\
        php artisan serve --host 0.0.0.0 --port 80"
    ports:
      - "8002:80"
    env_file:
      - ../.env
      - ../.env.testing
    volumes:
      - ../:/var/www/html:rw
    networks:
      - app_network

  mysql:
    image: mysql:8
    container_name: tracking_app_db
    ports:
      - "3308:3306"
    restart: "always"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - app_network

  redis:
    image: redis:6-alpine
    container_name: tracking_app_cache
    ports:
      - "6381:6379"
    volumes:
      - cache_data:/data
    networks:
      - app_network

volumes:
  db_data:
    driver: "local"
  cache_data:
    driver: "local"

networks:
  app_network:
    driver: "bridge"
